# Copyright 2025 Ron Parker

name: 'Build My Atreus'
on:
  - workflow_dispatch
jobs:
  build:
    uses: ./.github/workflows/main.yml
    with:
      keyboard: '["keyboardio/atreus"]'
      alphas: '["Dvorak"]'
      nav: '["invertedT"]'
      layers: '["flip"]'
      custom_config: '["#define MIRYOKU_TAP_QWERTY\n#define MIRYOKU_EXTRA_QWERTY"]'
